### ISSUE TITLE
falla el cron curl "http://clinicadolororofacial.es/citas/reminders.php?code=1234"

### ISSUE THREAD

**Issue by jgpATs2w** [jgpATs2w/booking#11]
Debido al bloqueo del dominio se ha parado de nuevo.
Paso a probar con https://cron-job.org/
la cuenta es jgp@sens2web.es:jgp134679

**Comment by alvaroatm** [comment]
Thanks!!! 

Ahora ya si o si funcionara... No?


En cumplimiento del artículo 5 de la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal, sus datos personales serán incluidos en el fichero "Historial Clínico" con la finalidad de Gestión de los Datos de los Pacientes y de su Historia Clínica y de las Tareas Administrativas Derivadas de la Prestación Asistencial. Puede ejercer sus derechos A.R.C.O. a Alvaro Parra en el correo alvaroparra@clinicadolororofacial.es


Antes de imprimir, por favor considere el medio ambiente.
Este mensaje y, en su caso, los archivos adjuntos son confidenciales y sólo pueden ser utilizados por su legítimo destinatario. En cumplimiento de las leyes vigentes en materia de protección de datos, si no desea seguir recibiendo mensajes de nuestra firma, por favor responda expresándonos su voluntad. Gracias.

**Comment by jgpATs2w** [comment]
Si primo, habían vuelto a bloquearnos la ip en varias listas negras 
porque alguien se ha dedicado a hacer cosas malas desde nuestros 
servidores... Tenemos un servidor de hosting 'Hosteurope' que es un 
desastre...
La solución esta vez ha sido emplear un servicio para la ejecución de 
tareas cron como la de los reminders, hasta que tenga otro servidor 
(posiblemente lo deje como backup mas adelante). Por el momento así se 
queda...
Besos

**Comment by jgpATs2w** [comment]
Issue moved to [jgpATs2w/clinic-reservation #7](https://github.com/jgpATs2w/clinic-reservation/issues/7) via [**ZenHub**](https://www.zenhub.com/)
