### ISSUE TITLE
Integración con facebook

### ISSUE THREAD

**Issue by jgpATs2w** [jgpATs2w/booking#14]
https://developers.facebook.com/docs/pages/publishing

**Comment by eBug** [comment]
Lo estuve mirando eso un poco hoy, lo que realmente ofrecen en el enlace que mencionas, es como publicar entre una página de FB y una app... de Facebook también, no tengo claro que se pueda hacer desde una web de terceros, hay que investigar.

**Comment by alvaroatm** [comment]
en principio ahora se utiliza en muchas paginas la autentificacion mediante fb, pero no se si esas paginas tienen algun permiso especial.... hoy me llamaron de https://www.shore.com/es/ tienen un sistema parecido al que tengo en mente, pero con coste mensual de mantenimiento... que es lo que se trata de evitar...

**Comment by eBug** [comment]
Una cosa es la publicación en FB, de lo que trata tu primer comentario. Otra es la autenticación. Mi comentario anterior se refería a la primera.

**Comment by jgpATs2w** [comment]
Issue moved to [jgpATs2w/booking-manager #25](https://github.com/jgpATs2w/booking-manager/issues/25) via [**ZenHub**](https://www.zenhub.com/)
