### ISSUE TITLE
referencias: analizar fortalezas, debilidades,...

### ISSUE THREAD

**Issue by jgpATs2w** [jgpATs2w/booking#16]
Para el diseño de la interfase y la funcionalidad, vamos a tomar algunas referencias de aplicaciones del mercado:
shore: tenemos acceso?
http://haicku.cliniko.com/: entrar con jgp@sens2web.es:jgp134679 (evaluación de 30 días)

**Comment by jgpATs2w** [comment]
Email de comercial de Shore:
 **Reserva Online**: tus clientes podrían reservar cita cualquier día a cualquier hora, vía online, con un botón directo en tu página web y en tu perfil de facebook, viendo la disponibilidad de tus servicios (0€ comisión por reserva). Súper útil para primeras citas! y que no pierdas clientes sino puedes atender el teléfono.
·  **Recordatorios por SMS**: envío programado de mensajes recordatorio para que los clientes no olviden sus reservas y así evitar plantones de ultima hora. 
·  **Newsletter**: envío personalizado de newsletter cada vez que quieras comunicar una promoción, un nuevo servicio o producto. Mediante nuestro recordatorio automático de reservas (sms y mail), disminuirán de forma muy considerable los imprevistos de última hora (cancelaciones y plantones).
·  **Agenda en la nube**: acceso directo y en todo momento a tu agenda, a la base de datos de tus clientes y a sus próximas reservas. Todo desde cualquier dispositivo con internet.
·  **Base datos de clientes**: la digitalización de tu base de datos de clientes te permitirá tener sus datos siempre actualizados y reforzar la relación con tus clientes.
· **Feedback**: nunca recibir opiniones de tus clientes fue más sencillo. Mediante la función feedback automático, ofrece a tus clientes la posibilidad de valorar la calidad de tus servicios.
·  **Posicionamiento**: ayudamos a la captación de nuevos clientes con la inclusión de tu negocio en nuestra de red de socios.
·  **Página web**: diseño web moderno, mantenimiento de la web y posicionamiento SEO. 
Te paso alguos ejemplos para que entiendas nuestro botón de reservas: (Mira el botón de reservas de las webs):
·  http://www.fisioterapiaaravaca.com/
·  http://vmedicatrix.com/

**Comment by jgpATs2w** [comment]
Buscando ejemplos de cliniko, he encontrado que uno de sus clientes ha cambiado de plataforma:
https://fchn.janeapp.com

**Comment by jgpATs2w** [comment]
Al fin, un cliente de cliniko que sigue con ellos ;):
https://backpainwestlondon.cliniko.com/bookings#service

**Comment by alvaroatm** [comment]
tambien tengo un perfil aqui...

http://www.fisioagenda.es/fisios/login.php?

Usuario: info@clinicadolororofacial.es.
Password: 20aea6a4
