### ISSUE TITLE
Funcionalidades

### ISSUE THREAD

**Issue by jgpATs2w** [jgpATs2w/booking#17]
Del análisis de otras plataformas, se extraen las siguientes funcionalidades deseadas:
- **Autenticación** con Gmail, Facebook o sistema propio
- **Citas**: tanto clientes como terapeutas podrán hacer reservas 1click en la semana.
- Botón de citas online para web y facebook.
- **Comunicación**: las citas se recuerdan con x horas de anticipación, dentro de un horario definido. Tanto emails como sms podrán responderse y se unirá a un hilo de conversación.
- **Feedbacks**: las respuestas de los clientes y las encuestas generarán información publicable por la clínica mediante widget (previa revisión)
- Gestión de **usuarios**: almacentamiento y edición en panel de control de los datos de los clientes: nombre, email, tlf y tipo.
- **Panel de control** adaptado al tipo de usuario:
  + Cliente: puede actualizar sus datos, ver sus citas y los comentarios sobre ellas, hacer nuevas reservas y eliminarlas.
  + Terapeuta:
     * cliente + cancelar citas de otros usuarios + editar/ver datos clientes de su clínica +  facturas...
    * Podrá definir los periodos (días de la semana, horas del día) en los que está disponible su servicio. Pudiendo excluir intervalos de fechas concretas.
  + Administrador: control total desde el panel de control.
- Gestión de **salas**
- Gestión de **servicios**: cada servicio tiene un precio y un terapeuta asociado.
- Gestión de **facturas**: selección, entre fechas, de citas, con totalización del coste.

**Comment by jgpATs2w** [comment]
![screenshot_20170515-145615](https://cloud.githubusercontent.com/assets/4340243/26059742/16c22278-3983-11e7-849f-8d9c7b48917d.png)
![screenshot_20170515-151446](https://cloud.githubusercontent.com/assets/4340243/26059747/1b51b0b0-3983-11e7-9d1a-e80466d62007.png)
![screenshot_20170515-145615](https://cloud.githubusercontent.com/assets/4340243/26059754/1edc5082-3983-11e7-9972-f618b3de606c.png)

**Comment by alvaroatm** [comment]
-Permitir generar tag o etiquetas a los pacientes, prefiere tardes, llega tarde, 10% decuento, etc.... que permita segmentarlos para poder, por ejemplo hacer mailing segmentado.
-Las respuestas de los mails, enriquecidas, que lleguen directamente a la posible anulacion o consultar detalles... aunque esto no afecta a la estructura de la base de datos...
-
<img width="585" alt="captura de pantalla 2017-05-17 a las 22 34 17" src="https://cloud.githubusercontent.com/assets/9497689/26174875/0e76b71c-3b51-11e7-8c4a-a37e509cd441.png">

la verdad es que lo anterior escrito por javi es muy completo, no se me ocurren muchas mas funciones que afecten a la estructura de la base de datos

**Comment by jgpATs2w** [comment]
También puedes tachar alguna, jeje

**Comment by alvaroatm** [comment]
deberiamos incluir el pago online cuando se realiza la reserva, yo no he implementado eso nunca ni creo que lo haga, pero hay mucha gente que lo hace.

**Comment by alvaroatm** [comment]
Integracion con otros programas de gestion. Yo tengo un programa de gestion de clinicas dentales en la otra clinica, que podriais mirar para ver si eso es posbile, pero creo que eso puede ser un handicap importante, ya que muchas de las clinicas poseen ese tipo de programas y si no es posible integrar lo echaran para atras. 

Shore no se puede integrar con el programa, porque he hablado directamente con ellos....

**Comment by alvaroatm** [comment]
Existe otro genial programa de gestion y de citas online, que se llama dricloud... por si quereis echarle un vistazo

**Comment by jgpATs2w** [comment]
¿Cuál es el nombre del programa de gestión que empleas? ¿Cuál es el de 
uso más generalizado?

**Comment by alvaroatm** [comment]
Nemotec es el programa que empleamos, este es famoso.... pregunto y te digo cuales mas hay...

**Comment by jgpATs2w** [comment]
A priori veo complicada la integración, no parece software abierto a 
este tipo de cosas, deberían tener una API publica.
La integración con Google e iCal si son posibles, y supongo que estas 
aplicaciones también podrán sincronizarse con estos calendarios... no?

**Comment by alvaroatm** [comment]
otro de los mas frecuentes es gestdent... el lunes hablo con nemotec y te cuento sobre la integracion con google y ical...

**Comment by jgpATs2w** [comment]
¿Sabemos algo de nemotec?
