### ISSUE TITLE
como usuario deseo seleccionar la cita rápidamente

### ISSUE THREAD

**Issue by jgpATs2w** [jgpATs2w/booking#2]

**Comment by alvaroatm** [comment]
deberiamos permiterle ver los huecos libres y que al seleccionar el que desea le pida la informacion para sign in or sign up... el sign up mediante identificacion en redes sociales o simplemente con los datos de nombre, telefono e email.

**Comment by jgpATs2w** [comment]
Entondes es como hasta ahora, pero con la opción de inicio con usuario de facebook, gmail,...
